image: node:14-alpine

cache:
  key: sso
  paths:
    - node_modules/
    - vendor/

stages:
  - deploy

before_script:
  - apk add --update openssh-client rsync
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - apk --update add git wget curl php7 php7-curl php7-openssl php7-iconv php7-json php7-mbstring php7-phar php7-dom --repository http://nl.alpinelinux.org/alpine/edge/testing/ && rm /var/cache/apk/*
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  - composer install
  - npm install

deploy:
  stage: deploy
  artifacts:
    paths:
      - dist/
  only:
    - master
  script:
    - npm run deploy
    - rsync -a --delete --progress --rsh='ssh -p4975' dist/templates/sso/ sso@intern.redweb.dk:/home/sso/public_html/templates/sso

